accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts.views import SubmittableLoginView, SubmittablePasswordChangeView, SignUpView, ProfileView
from accounts.views import permissions_request_form


app_name = 'accounts'

urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('permissions-request-form/', permissions_request_form, name='permissions_request_form'),
]

hollymovies/urls.py
from django.contrib import admin
from django.urls import path, include

from viewer import urls as viewer_urls
from viewer.views import index
from accounts import urls as accounts_urls

from django.conf import settings
from django.conf.urls.static import static

# Functia include() include path-uri din alte apps
# care au un fisier urls.py in interiorul lor
urlpatterns = [
    # Url-ul pentru pagina de login
    # path('accounts/login/', LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('', index),
    path('movies/', include(viewer_urls)),
    path('accounts/', include(accounts_urls , namespace='accounts'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ^ adauga urls extra pentru fiecare fisier din folderul static/

viewer/urls.py
from django.urls import path, reverse

from viewer.views import MoviesView, MoviesViewDetail, GenreMoviesView, MovieCreateView, MovieDeleteView, MovieUpdateView

# Important: Atunci cand avemt path-uri definite in alte apps
# in fisierul urls.py din acel app trebuie sa existe o lista
# numita 'urlpatterns' in care ne definim path-urile in mod normal
urlpatterns = [
    path('', MoviesView.as_view(), name='movie-list'),
    path('update/<pk>', MovieUpdateView.as_view(), name='movie-update'),
    path('delete/<pk>', MovieDeleteView.as_view(), name='movie-delete'),
    path('create', MovieCreateView.as_view(success_url='/'), name='movie_create'),
    path('<slug:slug>', MoviesViewDetail.as_view(), name='movie-detail'),
    path('genre/<str:genre_name>', GenreMoviesView.as_view(), name='genre-movies-list'),
]

viewer/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
from django.db.models import CharField, Model, ForeignKey, DO_NOTHING, IntegerField, DateField, TextField, \
    DateTimeField, SlugField


class Genre(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.CharField(max_length=100)
    biography = models.TextField()
    birth_date = models.DateField()
    EYE_COLOR_CHOICES = [
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('hazel', 'Hazel'),
        ('dark', 'Dark'),
    ]
    eye_color = models.CharField(max_length=5, choices=EYE_COLOR_CHOICES)

    def __str__(self):
        return self.name

class Movie(Model):
    title = CharField(max_length=128)
    genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    rating = IntegerField()
    released = DateField()
    description = TextField()
    created = DateTimeField(auto_now_add=True)
    slug = SlugField(unique=True, editable=False)
    actors = models.ManyToManyField(Actor, related_name='movies')


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

viewer/forms.py
import re
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import (
    CharField, DateField, Form, IntegerField, ModelChoiceField, Textarea, DateInput, ModelForm
)

from viewer.models import Genre, Movie


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')

class DateInput(DateInput):
    input_type = 'date'



class MyModelForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        widgets = {
            'my_date': DateInput()
        }

class PastMonthField(DateField):

    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=result.day)

class MovieForm(ModelForm):

    #If I add this class Django is creating the rest of the fields by himself
    class Meta:
        model = Movie
        fields = '__all__'
    # So I can comment the fields where i didn't inserted unique specifications
    title = CharField(max_length=128)
    # genre = ModelChoiceField(queryset=Genre.objects)
    rating = IntegerField(min_value=1, max_value=10)
    released = PastMonthField(widget=DateInput)
    # description = CharField(widget=Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean_description(self):
        # Force each sentence of the description to be capitalized.
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'commedy' and result['rating'] > 5:
            self.add_error('genre' '')
            self.add_error('rating' '')
            raise ValidationError(
                "Commedies aren't so good to be rated over 5."
            )
        return result

viewer/views.py
from django.db.models.expressions import result
from django.shortcuts import render, redirect
from django.template.defaultfilters import title
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from viewer.forms import MovieForm
from viewer.mixins import StaffRequiredMixin
from viewer.models import Movie, Genre, Actor


# Create your views here.
# class MoviesView(View):
#     def get(self, request):
#         return render(request, template_name='movies.html',
#                       context={'movies': Movie.objects.all()})

# class MoviesView(TemplateView):
#     template_name = 'movies.html'
#     extra_context = {'movies': Movie.objects.all()}

def index(request):
    return redirect('/movies')


# CRUD: Create, Read, Update, Delete
# Read - folosim HTTP GET
# Create, Update, Delete - folosim HTTP POST

class MoviesView(ListView):
    template_name = 'movies.html'
    model = Movie

class MoviesViewDetail(PermissionRequiredMixin, DetailView):
    template_name = 'movies_detail.html'
    model = Movie

    # pentru numele permisiunilor: '<nume-app>.<actiuni>_<nume-model>'
    permission_required = 'viewer.view_movie'

class GenreMoviesView(ListView):
    template_name = 'movies.html'
    model = Movie

    def get_queryset(self):
        qs = super().get_queryset()
        genre = Genre.objects.get(name=self.kwargs['genre_name'])
        return qs.filter(genre=genre)


class ActorDetailView(DetailView):
    template_name = 'actor_detail.html'
    model = Actor


class MovieCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = MovieForm
    permission_required = 'viewer.add_movie'

    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     cleaned_data = form.cleaned_data
    #     Movie.objects.create(
    #         title = cleaned_data['title'],
    #         genre=cleaned_data['genre'],
    #         rating=cleaned_data['rating'],
    #         released=cleaned_data['released'],
    #         description=cleaned_data['description']
    #     )
    #     return result

    def form_invalid(self, form):
        print('User provided invalid data')
        return super().form_invalid(form)

class MovieUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('movie-list')
    permission_required = 'viewer.change_movie'

    def form_invalid(self, form):
        print('User provided invalid data')
        return super().form_invalid(form)

class MovieDeleteView(StaffRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('movie-list')
    permission_required = 'viewer.delete_movie'

viewer/templates/actor_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ actor.first_name }} {{ actor.last_name }}</h1>
    <p><strong>Bio:</strong> {{ actor.biography }}</p>
    <p><strong>Birth Date:</strong> {{ actor.birth_date }}</p>
    <p><strong>Eye Color:</strong> {{ actor.get_eye_color_display }}</p>
{% endblock %}

viewer/templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}" {% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HollyMovies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">HollyMovies</a>
        <button
                class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="/">
                    Home
                </a>
            </div>
        </div>
        <div class="nav-item dropdown ml-auto">
            {% if user.is_authenticated %}
            <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" data-toggle="dropdown">
                {% if user.first_name  %} Hello, {{ user.first_name }}!
                {% else %} Hello, {{ user.username }} {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropdown">
                <a class="dropdown-item" href="{% url 'accounts:profile' %}">View Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
            {% else %}
            <a class="nav-link dropdown-toggle text-white" href="#" id="guestDropdown" data-toggle="dropdown">
                You are not logged in.
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="guestDropdown">
                <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            </div>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container">
    <div class="jumbotron">
        {% block content %}{% endblock %}
    </div>
</div>
</body>

</html>

viewer/templates/form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <!-- form.non_field_errors = erori generale din form  -->
    {{ form.non_field_errors }}
    <div class="form-group">
        <!-- Erori care tin de un field anume, in acest caz de field-ul title  -->
        {{ form.title.errors }}
        <label for="{{ form.title.id_for_label }}">Title:</label>

        <!-- Field-uri individuale din formular -->
        <!-- Numele lor sunt aceleasi ca formularul declarat in forms.py -->
        {{ form.title }}
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                {{ form.genre.errors }}
                <label for="{{ form.genre.id_for_label }}">Genre:</label>
                {{ form.genre }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                {{ form.rating.errors }}
                <label for="{{ form.rating.id_for_label }}">Rating:</label>
                {{ form.rating }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                {{ form.released.errors }}
                <label for="{{ form.released.id_for_label }}">Released:</label>
                {{ form.released }}
            </div>
        </div>
    </div>
    <div class="form-group">
        {{ form.description.errors }}
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/movie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object.title }}?</p>
  <input type="submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to HollyMovies!</h1>

<ul>
    {% for movie in object_list %}
    <li>
        <a href="{% url 'movie-detail' movie.slug %}"> {{ movie.title }} ({{ movie.released.year }}) - {{ movie.genre.name }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

viewer/templates/movies_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Titlu: {{ object.title }}</h1>
<p>Descriere: {{ object.description }}</p>
{% endblock %}